version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_PORT=19002
    command: npm start
    stdin_open: true
    tty: true 